Repository Imposter-study/Beta, pull requests merged in 2025-06, with the labels that each got.

#12 Feature/accounts profile
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_username.py
  accounts/migrations/0003_alter_user_username.py
  accounts/migrations/0004_alter_user_age_alter_user_gender.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  beta/settings.py
  beta/urls.py
  requirements.txt
Labels: merge

#32 ✨ Feat : add characters app
  beta/settings.py
  beta/urls.py
  characters/__init__.py
  characters/admin.py
  characters/apps.py
  characters/migrations/0001_initial.py
  characters/migrations/__init__.py
  characters/models.py
  characters/serializers.py
  characters/tests.py
  characters/urls.py
  characters/views.py
  requirements.txt
Labels: enhancement

#36 Feature/allauth/kakao
  accounts/adapters.py
  accounts/migrations/0005_remove_user_age_user_birth_date.py
  accounts/migrations/0006_alter_user_email.py
  accounts/migrations/0007_merge_20250617_1700.py
  accounts/models.py
  accounts/urls.py
  accounts/views.py
  beta/settings.py
  requirements.txt
Labels: enhancement

#42 Feature/allauth/google
  accounts/adapters.py
  accounts/urls.py
  accounts/views.py
  beta/settings.py
  requirements.txt
Labels: enhancement

#44 Refator/room/model
  room/migrations/0003_room_user.py
  room/migrations/0004_alter_room_character_id.py
  room/models.py
  room/services.py
  room/views.py
Labels: Refactoring

#48 Feature/room/character
  beta/settings.py
  room/migrations/0005_room_uuid_id.py
  room/migrations/0006_remove_chat_room_remove_room_user_alter_room_room_id_and_more.py
  room/migrations/0007_remove_room_room_id_chat_room.py
  room/migrations/0008_rename_uuid_id_room_room_id.py
  room/migrations/0009_room_user.py
  room/migrations/0010_alter_room_character_id_alter_room_created_at_and_more.py
  room/models.py
  room/serializers.py
  room/services.py
  room/urls.py
  room/views.py
Labels: enhancement

#49 Feature/accounts/profileimage2
  Dockerfile
  accounts/migrations/0008_user_profile_picture.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  requirements.txt
Labels: merge

#51 Feature/accounts/autonickname
  accounts/migrations/0008_user_profile_picture_alter_user_nickname.py
  accounts/models.py
  accounts/serializers.py
Labels: enhancement

#55 Deploy/dockerfile
  Dockerfile
  beta/settings.py
  docker-compose.yml
  gunicorn.conf.py
  nginx.conf
  requirements.txt
Labels: Deploy
