Repository Imposter-study/Beta, pull requests merged in 2025-07, with the labels that each got.

#73 Refator/rooms/urls
  beta/settings.py
  characters/migrations/0007_hashtag_character_hashtags.py
  rooms/migrations/0002_alter_chat_content_alter_room_character_id_and_more.py
  rooms/models.py
  rooms/serializers.py
  rooms/services.py
  rooms/urls.py
  rooms/views.py
Labels: Refactoring

#74 Feature/characters/hashtag search
  characters/views.py
Labels: enhancement

#76 ✨ Feat: add Kakao login redirect template
  accounts/templates/accounts/redirect.html
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#79 Refator/accounts
  accounts/serializers.py
  accounts/views.py
  characters/serializers.py
Labels: Refactoring

#80 Refactor/rooms/feild
  accounts/views.py
  characters/migrations/0009_rename_character_character_character_id_and_more.py
  characters/models.py
  characters/serializers.py
  characters/urls.py
  characters/views.py
  rooms/migrations/0002_alter_room_character_id.py
  rooms/migrations/0003_merge_20250701_1452.py
  rooms/migrations/0004_alter_room_character_id.py
  rooms/migrations/0005_merge_0003_room_fixation_0004_alter_room_character_id.py
  rooms/migrations/0006_rename_character_id_room_character_alter_room_user.py
  rooms/models.py
  rooms/serializers.py
  rooms/services.py
  rooms/views.py
Labels: Refactoring

#84 Fix/rooms/history
  rooms/serializers.py
  rooms/urls.py
  rooms/views.py
Labels: bug

#91 👷 Add: CICD file
  .github/workflows/Beta_cicd.yml
Labels: Deploy

#94 💚 Fix: CI Build
  .github/workflows/Beta_cicd.yml
Labels: Fix

#95 💚 Fix: CI/CD
  .github/workflows/Beta_cicd.yml
Labels: Fix

#93 Refactor/accounts
  characters/serializers.py
  characters/views.py
Labels: Refactoring

#97 Fix: CICD
  .github/workflows/Beta_cicd.yml
Labels: Fix

#98 💚 Fix: cicd
  .github/workflows/Beta_cicd.yml
Labels: Fix

#101 🐛 Fix: characters search_characters
  characters/views.py
Labels: bug

#102 Feature/characters/scrap
  characters/serializers.py
Labels: enhancement

#104 ♻️ Refactor : characters userprofile
  characters/serializers.py
Labels: Refactoring

#105 ✨ Feat: chatprofile_uuid
  accounts/serializers.py
  accounts/views.py
Labels: merge

#107 Feature/accounts/UUID
  accounts/migrations/0013_alter_follow_unique_together_remove_chatprofile_user_and_more.py
  accounts/migrations/0014_remove_user_id_alter_user_uuid.py
  accounts/migrations/0015_chatprofile_user_follow_from_user_follow_to_user_and_more.py
  accounts/migrations/0016_alter_user_nickname_alter_user_username.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  beta/settings.py
  characters/migrations/0013_remove_character_user_and_more.py
  characters/migrations/0014_character_user_conversationhistory_user.py
  characters/serializers.py
  rooms/migrations/0011_remove_room_user.py
  rooms/migrations/0012_room_user.py
Labels: Refactoring
